// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package data

import (
	"database/sql"
)

type Author struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Quote struct {
	ID       int32         `json:"id"`
	AuthorID sql.NullInt32 `json:"author_id"`
	Quote    string        `json:"quote"`
}
