[package]
name = "tar"
version = "0.1.0"
authors = ["Robert Narvaez <narvaez.rm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
